### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Tuanbeodayy22** [toschief/Dell-Latitude-7400-Hackintosh#1]
**Describe the problem**
A clear and concise description of what the problem is.

**How to reproduce**
Steps to reproduce the problem.

**Possible solution**
What you think could be the solution.

**Screenshots**

**Version**
MacOS and EFI versions.

**Your System**
Describe your hardware if it is different.

**Additional context**

**Comment by toschief** [comment]
???

**Comment by toschief** [comment]
Issue not clear. Will be closed if nothing changes.
